config/routes.rb
Viking::Application.routes.draw do
  
  resources :items, :sessions, :categories

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'menu' => 'items#index'

   root :to => "items#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :title, :message => "can't be empty"
  validates_presence_of :description, :message => "can't be empty"
  validates_presence_of :number, :message => "can't be empty" 
  validates_presence_of :price, :message => "can't be empty" 
  validates_uniqueness_of :title, :message => "has already been taken"
  validates_uniqueness_of :description, :message => "has already been taken"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  helper_method :admin?
  
  protected

  def authorize
    unless admin?
      redirect_to(:root, :alert => 'Unauthorized Access')
    end
  end

  def admin?
    session[:password] == "viking"
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authorize
  
  def index
    @categories = Category.find(:all, :order => 'name')
  end


  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
      if @category.save
        redirect_to(categories_url, :notice => 'Category was successfully created.')
      else
        render :action => "new"
    end
  end

  def update
    @category = Category.find(params[:id])
      if @category.update_attributes(params[:category])
        redirect_to(categories_url, :notice => 'Category was successfully updated.')
      else
        render :action => "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
      redirect_to(categories_url)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authorize, :except => [:index]
  
  def index
     @items = Item.find(:all, :order => 'created_at ASC')
     @items_by_category = @items.group_by(&:category)
  end

  def new
    @item = Item.new
    render :layout => "item_form"
  end

  def edit
    @item = Item.find(params[:id])
    render :layout => "item_form"
  end

  def create
    @item = Item.new(params[:item])
      if @item.save
        redirect_to(items_url, :notice => 'Item was successfully created.')
      else
        render :action => "new", :layout => 'item_form'
    end
  end

  def update
    @item = Item.find(params[:id])
      if @item.update_attributes(params[:item])
        redirect_to(items_url, :notice => 'Item was successfully updated.')
      else
        render :action => "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to(items_url, :notice => 'Item was successfully deleted.')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   layout "session"
  def new
   
  end

  def create
    session[:password] = params[:password]
    if
      session[:password] == "viking"
      redirect_to(:root, :notice => 'Sucessfully logged in')
    else
      redirect_to(login_path, :alert => 'Wrong password')
    end
  end

  def destroy
    reset_session
    redirect_to(:root, :notice => 'Sucessfully logged out')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="categories">
	<h1>Editing category</h1>
	<%= render 'form' %>
	<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="categories">
	<% if admin? %>
		<%= link_to 'New Category', new_category_path, :class => 'brown_button' %>
	<% end -%>	
	<ul>
		<% @categories.each do |category| %>
			<li>
				<%= category.name %>
				<% if admin? %>
    			<%= link_to 'Edit', edit_category_path(category), :class => 'admin_button' %>
    			<%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete, :class => 'admin_button' %>
				<% end -%>
			</li>	
		<% end %>
	</ul>	
</div><!-- END .categories -->

app/views/categories/new.html.erb
<div class="categories">
	<h1>Create a new category</h1>
	<%= render 'form' %>
	<%= link_to 'Back', categories_path %>
</div>

app/views/items/_form.html.erb
<%= form_for(@item, :html => {:class => "form-horizontal" }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> stopped you creating this menu item:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :category, :class => "control-label" %>
    <div class="controls">
      <%= collection_select(:item, :category_id, Category.find(:all), :id, :name) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :number, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :number, :class => "input-small" %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class => "input-large" %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :description, :class => "input-large" %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :price, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :price, :class => "input-small" %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit :class => 'btn' %>
    <%= link_to 'Cancel', items_path, :id => 'new_back_button' %>
  </div>
    
<% end %>

app/views/items/edit.html.erb
<div class="form_box_item">
	<%= image_tag "edit_item_heading.png", :class => 'header_image' %>
	<%= render 'form' %>
<!-- END .form_box --></div>

app/views/items/index.html.erb
<% if admin? %>
	<%= link_to 'New Item', new_item_path, :class => 'brown_button', :id => 'new_item_button' %>
<% end -%>	

<% @items_by_category.each do |category, items| %>
	<% if category %>
		<h3 class="category_heading"><%= category.name %></h3>
			<table class="menu_table">
				<% for item in items %>
  				<tr class="normal_row">
    				<td class="number"><%= item.number %></td>
    				<td class="title">
							<%= item.title %>
							<% if admin? %>
								<%= link_to 'Edit', edit_item_path(item), :class => 'admin_button' %>
								<%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete, :class => 'admin_button' %>
							<% end -%>
							</td>
    				<td class="price"><%= item.price %></td>
					</tr>	
					<tr class="description_row">
						<td></td>
    				<td><span class="smaller_menu_text"><%= item.description %></span></td>
    				<td></td>	
  				</tr>
				<% end %>
			</table>
	  <% end %>
<% end -%>

app/views/items/new.html.erb
<div class="form_box_item">
	<%= image_tag "new_item_heading.png", :class => 'header_image' %>
	<%= render 'form' %>
<!-- END .form_box --></div>

app/views/layouts/_form_only_bottom.html.erb
	<!-- END .form_content --></div>
<!-- END #wrapper --></div>
</body>
</html>

app/views/layouts/_form_only_top.html.erb
<body class="form_only">
<div id="wrapper">
	<div class="form_content">
		<div class="alert_message">
			<p class="alert_text"><%= alert %></p>
		<!-- END .alert --></div>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viking Pizza || Tananger, Norway</title>
  <meta name="description" content="Great Pizza, Kebab, Burgers and Salad, Tananger" />
  <meta name="keywords" content="Pizza, Kebab, Burgers, Salad, Tananger" />
	<%= favicon_link_tag %>
  <%= stylesheet_link_tag :all %>
	<%= javascript_include_tag "jquery-1.4.3" %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
	<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
	<link  href="http://fonts.googleapis.com/css?family=Allan:bold" rel="stylesheet" type="text/css" >
</head>

app/views/layouts/application.html.erb
<%= render :partial => 'layouts/head' %>
<body>
<div id="wrapper">
		<section id="header">
			<div id="flash">
				<p class="notice"><%= notice %></p>
				<p class="alert_text"><%= alert %></p>
			<!-- END #flash --></div>
			<div id="logo">
				<%= link_to "", :root, :id => 'logo_link' %>
				
			<!-- END #logo --></div>
			<div id="banner">
				<%= image_tag 'telephone.png', :id => 'telephone' %>			
			<!-- END #banner --></div>
		</section>	
		<section id="content">
			<div id="menu">
				<%= yield %>
			</div>
		</section>	
<!-- END #wrapper --></div>
</body>
</html>

app/views/layouts/item_form.html.erb
<%= render :partial => 'layouts/head' %>
<body class="form_only">
<div id="wrapper">
	<div class="form_content_item">
		<div class="alert_message">
			<p class="alert_text"><%= alert %></p>
		<!-- END .alert --></div>
<%= yield %>
	<!-- END .form_content --></div>
<!-- END #wrapper --></div>
</body>
</html>

app/views/layouts/session.html.erb
<%= render :partial => 'layouts/head' %>
<%= render :partial => 'layouts/form_only_top' %>
<%= yield %>
<%= render :partial => 'layouts/form_only_bottom' %>
	